"""Initial schema

Revision ID: 9372cec8298d
Revises:
Create Date: 2025-10-06 14:08:38.488763

"""


# revision identifiers, used by Alembic.
revision = '9372cec8298d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
